package com.seeu.userpay.model;

public class UserPayBank {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpay_bank.UID
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    private Integer UID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpay_bank.alipayID
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    private String alipayID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpay_bank.wechatID
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    private String wechatID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpay_bank.UID
     *
     * @return the value of userpay_bank.UID
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    public Integer getUID() {
        return UID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpay_bank.UID
     *
     * @param UID the value for userpay_bank.UID
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    public void setUID(Integer UID) {
        this.UID = UID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpay_bank.alipayID
     *
     * @return the value of userpay_bank.alipayID
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    public String getAlipayID() {
        return alipayID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpay_bank.alipayID
     *
     * @param alipayID the value for userpay_bank.alipayID
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    public void setAlipayID(String alipayID) {
        this.alipayID = alipayID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpay_bank.wechatID
     *
     * @return the value of userpay_bank.wechatID
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    public String getWechatID() {
        return wechatID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpay_bank.wechatID
     *
     * @param wechatID the value for userpay_bank.wechatID
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    public void setWechatID(String wechatID) {
        this.wechatID = wechatID;
    }
}