package com.seeu.userpay.model;

public class UserPayTransfer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpay_trans.id
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpay_trans.UID
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    private Integer UID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpay_trans.toUID
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    private Integer toUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpay_trans.money
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    private Integer money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpay_trans.paytype
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    private String paytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpay_trans.paybankID
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    private String paybankID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpay_trans.note
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpay_trans.id
     *
     * @return the value of userpay_trans.id
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpay_trans.id
     *
     * @param id the value for userpay_trans.id
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpay_trans.UID
     *
     * @return the value of userpay_trans.UID
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    public Integer getUID() {
        return UID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpay_trans.UID
     *
     * @param UID the value for userpay_trans.UID
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    public void setUID(Integer UID) {
        this.UID = UID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpay_trans.toUID
     *
     * @return the value of userpay_trans.toUID
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    public Integer getToUID() {
        return toUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpay_trans.toUID
     *
     * @param toUID the value for userpay_trans.toUID
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    public void setToUID(Integer toUID) {
        this.toUID = toUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpay_trans.money
     *
     * @return the value of userpay_trans.money
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpay_trans.money
     *
     * @param money the value for userpay_trans.money
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpay_trans.paytype
     *
     * @return the value of userpay_trans.paytype
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    public String getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpay_trans.paytype
     *
     * @param paytype the value for userpay_trans.paytype
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    public void setPaytype(String paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpay_trans.paybankID
     *
     * @return the value of userpay_trans.paybankID
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    public String getPaybankID() {
        return paybankID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpay_trans.paybankID
     *
     * @param paybankID the value for userpay_trans.paybankID
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    public void setPaybankID(String paybankID) {
        this.paybankID = paybankID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpay_trans.note
     *
     * @return the value of userpay_trans.note
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpay_trans.note
     *
     * @param note the value for userpay_trans.note
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    public void setNote(String note) {
        this.note = note;
    }
}