package com.seeu.userpay.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.seeu.userpay.model.UserPayBank;

public class UserPayBankSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpay_bank
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    public String insertSelective(UserPayBank record) {
        BEGIN();
        INSERT_INTO("userpay_bank");
        
        if (record.getUID() != null) {
            VALUES("UID", "#{UID,jdbcType=INTEGER}");
        }
        
        if (record.getAlipayID() != null) {
            VALUES("alipayID", "#{alipayID,jdbcType=VARCHAR}");
        }
        
        if (record.getWechatID() != null) {
            VALUES("wechatID", "#{wechatID,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpay_bank
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    public String updateByPrimaryKeySelective(UserPayBank record) {
        BEGIN();
        UPDATE("userpay_bank");
        
        if (record.getAlipayID() != null) {
            SET("alipayID = #{alipayID,jdbcType=VARCHAR}");
        }
        
        if (record.getWechatID() != null) {
            SET("wechatID = #{wechatID,jdbcType=VARCHAR}");
        }
        
        WHERE("UID = #{UID,jdbcType=INTEGER}");
        
        return SQL();
    }
}