package com.seeu.userpay.dao;

import com.seeu.userpay.model.UserPayBalance;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface UserPayBalanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpay_balance
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    @Delete({
        "delete from userpay_balance",
        "where UID = #{UID,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer UID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpay_balance
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    @Insert({
        "insert into userpay_balance (UID, balance)",
        "values (#{UID,jdbcType=INTEGER}, #{balance,jdbcType=DECIMAL})"
    })
    int insert(UserPayBalance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpay_balance
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    @InsertProvider(type=UserPayBalanceSqlProvider.class, method="insertSelective")
    int insertSelective(UserPayBalance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpay_balance
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    @Select({
        "select",
        "UID, balance",
        "from userpay_balance",
        "where UID = #{UID,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="UID", property="UID", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="balance", property="balance", jdbcType=JdbcType.DECIMAL)
    })
    UserPayBalance selectByPrimaryKey(Integer UID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpay_balance
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    @UpdateProvider(type=UserPayBalanceSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(UserPayBalance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpay_balance
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    @Update({
        "update userpay_balance",
        "set balance = #{balance,jdbcType=DECIMAL}",
        "where UID = #{UID,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserPayBalance record);
}