package com.seeu.userpay.dao;

import com.seeu.userpay.model.UserPayBank;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface UserPayBankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpay_bank
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    @Delete({
        "delete from userpay_bank",
        "where UID = #{UID,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer UID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpay_bank
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    @Insert({
        "insert into userpay_bank (UID, alipayID, ",
        "wechatID)",
        "values (#{UID,jdbcType=INTEGER}, #{alipayID,jdbcType=VARCHAR}, ",
        "#{wechatID,jdbcType=VARCHAR})"
    })
    int insert(UserPayBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpay_bank
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    @InsertProvider(type=UserPayBankSqlProvider.class, method="insertSelective")
    int insertSelective(UserPayBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpay_bank
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    @Select({
        "select",
        "UID, alipayID, wechatID",
        "from userpay_bank",
        "where UID = #{UID,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="UID", property="UID", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="alipayID", property="alipayID", jdbcType=JdbcType.VARCHAR),
        @Result(column="wechatID", property="wechatID", jdbcType=JdbcType.VARCHAR)
    })
    UserPayBank selectByPrimaryKey(Integer UID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpay_bank
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    @UpdateProvider(type=UserPayBankSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(UserPayBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpay_bank
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    @Update({
        "update userpay_bank",
        "set alipayID = #{alipayID,jdbcType=VARCHAR},",
          "wechatID = #{wechatID,jdbcType=VARCHAR}",
        "where UID = #{UID,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserPayBank record);
}