package com.seeu.userpay.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.seeu.userpay.model.UserPayTransfer;

public class UserPayTransferSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpay_trans
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    public String insertSelective(UserPayTransfer record) {
        BEGIN();
        INSERT_INTO("userpay_trans");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getUID() != null) {
            VALUES("UID", "#{UID,jdbcType=INTEGER}");
        }
        
        if (record.getToUID() != null) {
            VALUES("toUID", "#{toUID,jdbcType=INTEGER}");
        }
        
        if (record.getMoney() != null) {
            VALUES("money", "#{money,jdbcType=INTEGER}");
        }
        
        if (record.getPaytype() != null) {
            VALUES("paytype", "#{paytype,jdbcType=VARCHAR}");
        }
        
        if (record.getPaybankID() != null) {
            VALUES("paybankID", "#{paybankID,jdbcType=VARCHAR}");
        }
        
        if (record.getNote() != null) {
            VALUES("note", "#{note,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpay_trans
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    public String updateByPrimaryKeySelective(UserPayTransfer record) {
        BEGIN();
        UPDATE("userpay_trans");
        
        if (record.getUID() != null) {
            SET("UID = #{UID,jdbcType=INTEGER}");
        }
        
        if (record.getToUID() != null) {
            SET("toUID = #{toUID,jdbcType=INTEGER}");
        }
        
        if (record.getMoney() != null) {
            SET("money = #{money,jdbcType=INTEGER}");
        }
        
        if (record.getPaytype() != null) {
            SET("paytype = #{paytype,jdbcType=VARCHAR}");
        }
        
        if (record.getPaybankID() != null) {
            SET("paybankID = #{paybankID,jdbcType=VARCHAR}");
        }
        
        if (record.getNote() != null) {
            SET("note = #{note,jdbcType=VARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}