package com.seeu.userpay.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.seeu.userpay.model.UserPayBalance;

public class UserPayBalanceSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpay_balance
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    public String insertSelective(UserPayBalance record) {
        BEGIN();
        INSERT_INTO("userpay_balance");
        
        if (record.getUID() != null) {
            VALUES("UID", "#{UID,jdbcType=INTEGER}");
        }
        
        if (record.getBalance() != null) {
            VALUES("balance", "#{balance,jdbcType=DECIMAL}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpay_balance
     *
     * @mbggenerated Wed Jan 18 03:42:33 CST 2017
     */
    public String updateByPrimaryKeySelective(UserPayBalance record) {
        BEGIN();
        UPDATE("userpay_balance");
        
        if (record.getBalance() != null) {
            SET("balance = #{balance,jdbcType=DECIMAL}");
        }
        
        WHERE("UID = #{UID,jdbcType=INTEGER}");
        
        return SQL();
    }
}