package com.seeu.im.model;

public class IMBlackList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_blacklist.UID_from
     *
     * @mbggenerated Wed Jan 18 05:08:21 CST 2017
     */
    private Integer UID_from;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_blacklist.UID_to
     *
     * @mbggenerated Wed Jan 18 05:08:21 CST 2017
     */
    private Integer UID_to;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_blacklist.UID_from
     *
     * @return the value of im_blacklist.UID_from
     *
     * @mbggenerated Wed Jan 18 05:08:21 CST 2017
     */
    public Integer getUID_from() {
        return UID_from;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_blacklist.UID_from
     *
     * @param UID_from the value for im_blacklist.UID_from
     *
     * @mbggenerated Wed Jan 18 05:08:21 CST 2017
     */
    public void setUID_from(Integer UID_from) {
        this.UID_from = UID_from;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_blacklist.UID_to
     *
     * @return the value of im_blacklist.UID_to
     *
     * @mbggenerated Wed Jan 18 05:08:21 CST 2017
     */
    public Integer getUID_to() {
        return UID_to;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_blacklist.UID_to
     *
     * @param UID_to the value for im_blacklist.UID_to
     *
     * @mbggenerated Wed Jan 18 05:08:21 CST 2017
     */
    public void setUID_to(Integer UID_to) {
        this.UID_to = UID_to;
    }
}