package com.seeu.im.model;

public class IMFans {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_fans.UID_from
     *
     * @mbggenerated Wed Jan 18 05:08:21 CST 2017
     */
    private Integer UID_from;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_fans.UID_to
     *
     * @mbggenerated Wed Jan 18 05:08:21 CST 2017
     */
    private Integer UID_to;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_fans.relation
     *
     * @mbggenerated Wed Jan 18 05:08:21 CST 2017
     */
    private Integer relation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_fans.UID_from
     *
     * @return the value of im_fans.UID_from
     *
     * @mbggenerated Wed Jan 18 05:08:21 CST 2017
     */
    public Integer getUID_from() {
        return UID_from;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_fans.UID_from
     *
     * @param UID_from the value for im_fans.UID_from
     *
     * @mbggenerated Wed Jan 18 05:08:21 CST 2017
     */
    public void setUID_from(Integer UID_from) {
        this.UID_from = UID_from;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_fans.UID_to
     *
     * @return the value of im_fans.UID_to
     *
     * @mbggenerated Wed Jan 18 05:08:21 CST 2017
     */
    public Integer getUID_to() {
        return UID_to;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_fans.UID_to
     *
     * @param UID_to the value for im_fans.UID_to
     *
     * @mbggenerated Wed Jan 18 05:08:21 CST 2017
     */
    public void setUID_to(Integer UID_to) {
        this.UID_to = UID_to;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_fans.relation
     *
     * @return the value of im_fans.relation
     *
     * @mbggenerated Wed Jan 18 05:08:21 CST 2017
     */
    public Integer getRelation() {
        return relation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_fans.relation
     *
     * @param relation the value for im_fans.relation
     *
     * @mbggenerated Wed Jan 18 05:08:21 CST 2017
     */
    public void setRelation(Integer relation) {
        this.relation = relation;
    }
}