package com.seeu.user.model;

public class UserBusiness {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_business.recordID
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    private Integer recordID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_business.UID
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    private Integer UID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_business.time_start
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    private String time_start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_business.time_end
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    private String time_end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_business.company
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_business.company_province
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    private String company_province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_business.company_city
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    private String company_city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_business.comment
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_business.recordID
     *
     * @return the value of user_business.recordID
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public Integer getRecordID() {
        return recordID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_business.recordID
     *
     * @param recordID the value for user_business.recordID
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public void setRecordID(Integer recordID) {
        this.recordID = recordID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_business.UID
     *
     * @return the value of user_business.UID
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public Integer getUID() {
        return UID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_business.UID
     *
     * @param UID the value for user_business.UID
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public void setUID(Integer UID) {
        this.UID = UID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_business.time_start
     *
     * @return the value of user_business.time_start
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public String getTime_start() {
        return time_start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_business.time_start
     *
     * @param time_start the value for user_business.time_start
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public void setTime_start(String time_start) {
        this.time_start = time_start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_business.time_end
     *
     * @return the value of user_business.time_end
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public String getTime_end() {
        return time_end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_business.time_end
     *
     * @param time_end the value for user_business.time_end
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public void setTime_end(String time_end) {
        this.time_end = time_end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_business.company
     *
     * @return the value of user_business.company
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_business.company
     *
     * @param company the value for user_business.company
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_business.company_province
     *
     * @return the value of user_business.company_province
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public String getCompany_province() {
        return company_province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_business.company_province
     *
     * @param company_province the value for user_business.company_province
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public void setCompany_province(String company_province) {
        this.company_province = company_province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_business.company_city
     *
     * @return the value of user_business.company_city
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public String getCompany_city() {
        return company_city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_business.company_city
     *
     * @param company_city the value for user_business.company_city
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public void setCompany_city(String company_city) {
        this.company_city = company_city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_business.comment
     *
     * @return the value of user_business.comment
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_business.comment
     *
     * @param comment the value for user_business.comment
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment;
    }
}