package com.seeu.user.model;

public class UserSocialNet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_socialnet.UID
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    private Integer UID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_socialnet.qq
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_socialnet.weixin
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    private String weixin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_socialnet.blog
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    private String blog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_socialnet.email
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_socialnet.phone_prefix
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    private String phone_prefix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_socialnet.phone
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_socialnet.UID
     *
     * @return the value of user_socialnet.UID
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public Integer getUID() {
        return UID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_socialnet.UID
     *
     * @param UID the value for user_socialnet.UID
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public void setUID(Integer UID) {
        this.UID = UID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_socialnet.qq
     *
     * @return the value of user_socialnet.qq
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_socialnet.qq
     *
     * @param qq the value for user_socialnet.qq
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_socialnet.weixin
     *
     * @return the value of user_socialnet.weixin
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public String getWeixin() {
        return weixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_socialnet.weixin
     *
     * @param weixin the value for user_socialnet.weixin
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public void setWeixin(String weixin) {
        this.weixin = weixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_socialnet.blog
     *
     * @return the value of user_socialnet.blog
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public String getBlog() {
        return blog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_socialnet.blog
     *
     * @param blog the value for user_socialnet.blog
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public void setBlog(String blog) {
        this.blog = blog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_socialnet.email
     *
     * @return the value of user_socialnet.email
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_socialnet.email
     *
     * @param email the value for user_socialnet.email
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_socialnet.phone_prefix
     *
     * @return the value of user_socialnet.phone_prefix
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public String getPhone_prefix() {
        return phone_prefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_socialnet.phone_prefix
     *
     * @param phone_prefix the value for user_socialnet.phone_prefix
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public void setPhone_prefix(String phone_prefix) {
        this.phone_prefix = phone_prefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_socialnet.phone
     *
     * @return the value of user_socialnet.phone
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_socialnet.phone
     *
     * @param phone the value for user_socialnet.phone
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }
}