package com.seeu.user.model;

public class UserRealProfile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_realprofile.UID
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    private Integer UID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_realprofile.name
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_realprofile.idcard
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_realprofile.gender
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    private Integer gender;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_realprofile.UID
     *
     * @return the value of user_realprofile.UID
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public Integer getUID() {
        return UID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_realprofile.UID
     *
     * @param UID the value for user_realprofile.UID
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public void setUID(Integer UID) {
        this.UID = UID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_realprofile.name
     *
     * @return the value of user_realprofile.name
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_realprofile.name
     *
     * @param name the value for user_realprofile.name
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_realprofile.idcard
     *
     * @return the value of user_realprofile.idcard
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_realprofile.idcard
     *
     * @param idcard the value for user_realprofile.idcard
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_realprofile.gender
     *
     * @return the value of user_realprofile.gender
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_realprofile.gender
     *
     * @param gender the value for user_realprofile.gender
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }
}