package com.seeu.user.model;

public class UserEducation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_education.recordID
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    private Integer recordID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_education.UID
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    private Integer UID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_education.period
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    private Integer period;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_education.time_start
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    private String time_start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_education.time_end
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    private String time_end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_education.school
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    private String school;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_education.school_province
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    private String school_province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_education.school_city
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    private String school_city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_education.comment
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_education.recordID
     *
     * @return the value of user_education.recordID
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public Integer getRecordID() {
        return recordID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_education.recordID
     *
     * @param recordID the value for user_education.recordID
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public void setRecordID(Integer recordID) {
        this.recordID = recordID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_education.UID
     *
     * @return the value of user_education.UID
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public Integer getUID() {
        return UID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_education.UID
     *
     * @param UID the value for user_education.UID
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public void setUID(Integer UID) {
        this.UID = UID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_education.period
     *
     * @return the value of user_education.period
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public Integer getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_education.period
     *
     * @param period the value for user_education.period
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public void setPeriod(Integer period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_education.time_start
     *
     * @return the value of user_education.time_start
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public String getTime_start() {
        return time_start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_education.time_start
     *
     * @param time_start the value for user_education.time_start
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public void setTime_start(String time_start) {
        this.time_start = time_start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_education.time_end
     *
     * @return the value of user_education.time_end
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public String getTime_end() {
        return time_end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_education.time_end
     *
     * @param time_end the value for user_education.time_end
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public void setTime_end(String time_end) {
        this.time_end = time_end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_education.school
     *
     * @return the value of user_education.school
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_education.school
     *
     * @param school the value for user_education.school
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public void setSchool(String school) {
        this.school = school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_education.school_province
     *
     * @return the value of user_education.school_province
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public String getSchool_province() {
        return school_province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_education.school_province
     *
     * @param school_province the value for user_education.school_province
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public void setSchool_province(String school_province) {
        this.school_province = school_province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_education.school_city
     *
     * @return the value of user_education.school_city
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public String getSchool_city() {
        return school_city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_education.school_city
     *
     * @param school_city the value for user_education.school_city
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public void setSchool_city(String school_city) {
        this.school_city = school_city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_education.comment
     *
     * @return the value of user_education.comment
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_education.comment
     *
     * @param comment the value for user_education.comment
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment;
    }
}