package com.seeu.user.model;

public class UserProject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_proj.recordID
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    private Integer recordID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_proj.UID
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    private Integer UID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_proj.type
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_proj.title
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_proj.url
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_proj.role
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_proj.time_start
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    private String time_start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_proj.time_end
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    private String time_end;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_proj.recordID
     *
     * @return the value of user_proj.recordID
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    public Integer getRecordID() {
        return recordID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_proj.recordID
     *
     * @param recordID the value for user_proj.recordID
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    public void setRecordID(Integer recordID) {
        this.recordID = recordID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_proj.UID
     *
     * @return the value of user_proj.UID
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    public Integer getUID() {
        return UID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_proj.UID
     *
     * @param UID the value for user_proj.UID
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    public void setUID(Integer UID) {
        this.UID = UID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_proj.type
     *
     * @return the value of user_proj.type
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_proj.type
     *
     * @param type the value for user_proj.type
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_proj.title
     *
     * @return the value of user_proj.title
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_proj.title
     *
     * @param title the value for user_proj.title
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_proj.url
     *
     * @return the value of user_proj.url
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_proj.url
     *
     * @param url the value for user_proj.url
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_proj.role
     *
     * @return the value of user_proj.role
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_proj.role
     *
     * @param role the value for user_proj.role
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_proj.time_start
     *
     * @return the value of user_proj.time_start
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    public String getTime_start() {
        return time_start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_proj.time_start
     *
     * @param time_start the value for user_proj.time_start
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    public void setTime_start(String time_start) {
        this.time_start = time_start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_proj.time_end
     *
     * @return the value of user_proj.time_end
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    public String getTime_end() {
        return time_end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_proj.time_end
     *
     * @param time_end the value for user_proj.time_end
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    public void setTime_end(String time_end) {
        this.time_end = time_end;
    }
}