package com.seeu.user.model;

public class UserProjectWithBLOBs extends UserProject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_proj.note
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_proj.pictures
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    private String pictures;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_proj.performance
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    private String performance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_proj.note
     *
     * @return the value of user_proj.note
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_proj.note
     *
     * @param note the value for user_proj.note
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_proj.pictures
     *
     * @return the value of user_proj.pictures
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    public String getPictures() {
        return pictures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_proj.pictures
     *
     * @param pictures the value for user_proj.pictures
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    public void setPictures(String pictures) {
        this.pictures = pictures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_proj.performance
     *
     * @return the value of user_proj.performance
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    public String getPerformance() {
        return performance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_proj.performance
     *
     * @param performance the value for user_proj.performance
     *
     * @mbggenerated Wed Jan 18 15:24:24 CST 2017
     */
    public void setPerformance(String performance) {
        this.performance = performance;
    }
}