package com.seeu.user.model;

public class UserInterest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_interest.UID
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    private Integer UID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_interest.label
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    private String label;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_interest.UID
     *
     * @return the value of user_interest.UID
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public Integer getUID() {
        return UID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_interest.UID
     *
     * @param UID the value for user_interest.UID
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public void setUID(Integer UID) {
        this.UID = UID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_interest.label
     *
     * @return the value of user_interest.label
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_interest.label
     *
     * @param label the value for user_interest.label
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public void setLabel(String label) {
        this.label = label;
    }
}