package com.seeu.user.model;

public class UserBasic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_basic.UID
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    private Integer UID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_basic.icon
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_basic.name
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_basic.gender
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    private Byte gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_basic.birthday
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_basic.sign
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    private String sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_basic.location_province
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    private String location_province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_basic.location_city
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    private String location_city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_basic.home_province
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    private String home_province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_basic.home_city
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    private String home_city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_basic.register_time
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    private String register_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_basic.UID
     *
     * @return the value of user_basic.UID
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public Integer getUID() {
        return UID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_basic.UID
     *
     * @param UID the value for user_basic.UID
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public void setUID(Integer UID) {
        this.UID = UID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_basic.icon
     *
     * @return the value of user_basic.icon
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_basic.icon
     *
     * @param icon the value for user_basic.icon
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_basic.name
     *
     * @return the value of user_basic.name
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_basic.name
     *
     * @param name the value for user_basic.name
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_basic.gender
     *
     * @return the value of user_basic.gender
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_basic.gender
     *
     * @param gender the value for user_basic.gender
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_basic.birthday
     *
     * @return the value of user_basic.birthday
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_basic.birthday
     *
     * @param birthday the value for user_basic.birthday
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_basic.sign
     *
     * @return the value of user_basic.sign
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_basic.sign
     *
     * @param sign the value for user_basic.sign
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public void setSign(String sign) {
        this.sign = sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_basic.location_province
     *
     * @return the value of user_basic.location_province
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public String getLocation_province() {
        return location_province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_basic.location_province
     *
     * @param location_province the value for user_basic.location_province
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public void setLocation_province(String location_province) {
        this.location_province = location_province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_basic.location_city
     *
     * @return the value of user_basic.location_city
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public String getLocation_city() {
        return location_city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_basic.location_city
     *
     * @param location_city the value for user_basic.location_city
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public void setLocation_city(String location_city) {
        this.location_city = location_city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_basic.home_province
     *
     * @return the value of user_basic.home_province
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public String getHome_province() {
        return home_province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_basic.home_province
     *
     * @param home_province the value for user_basic.home_province
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public void setHome_province(String home_province) {
        this.home_province = home_province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_basic.home_city
     *
     * @return the value of user_basic.home_city
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public String getHome_city() {
        return home_city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_basic.home_city
     *
     * @param home_city the value for user_basic.home_city
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public void setHome_city(String home_city) {
        this.home_city = home_city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_basic.register_time
     *
     * @return the value of user_basic.register_time
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public String getRegister_time() {
        return register_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_basic.register_time
     *
     * @param register_time the value for user_basic.register_time
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public void setRegister_time(String register_time) {
        this.register_time = register_time;
    }
}