package com.seeu.im.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;

import com.seeu.im.model.IMBlackList;

public class IMBlackListSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_blacklist
     *
     * @mbggenerated Wed Jan 18 05:08:21 CST 2017
     */
    public String insertSelective(IMBlackList record) {
        BEGIN();
        INSERT_INTO("im_blacklist");
        
        if (record.getUID_from() != null) {
            VALUES("UID_from", "#{UID_from,jdbcType=INTEGER}");
        }
        
        if (record.getUID_to() != null) {
            VALUES("UID_to", "#{UID_to,jdbcType=INTEGER}");
        }
        
        return SQL();
    }
}