package com.seeu.im.dao;

import com.seeu.im.model.IMBlackList;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;

public interface IMBlackListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_blacklist
     *
     * @mbggenerated Wed Jan 18 05:08:21 CST 2017
     */
    @Insert({
        "insert into im_blacklist (UID_from, UID_to)",
        "values (#{UID_from,jdbcType=INTEGER}, #{UID_to,jdbcType=INTEGER})"
    })
    int insert(IMBlackList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_blacklist
     *
     * @mbggenerated Wed Jan 18 05:08:21 CST 2017
     */
    @InsertProvider(type=IMBlackListSqlProvider.class, method="insertSelective")
    int insertSelective(IMBlackList record);
}