package com.seeu.im.dao;

import com.seeu.im.model.IMFans;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;

public interface IMFansMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_fans
     *
     * @mbggenerated Wed Jan 18 05:08:21 CST 2017
     */
    @Insert({
        "insert into im_fans (UID_from, UID_to, ",
        "relation)",
        "values (#{UID_from,jdbcType=INTEGER}, #{UID_to,jdbcType=INTEGER}, ",
        "#{relation,jdbcType=INTEGER})"
    })
    int insert(IMFans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_fans
     *
     * @mbggenerated Wed Jan 18 05:08:21 CST 2017
     */
    @InsertProvider(type=IMFansSqlProvider.class, method="insertSelective")
    int insertSelective(IMFans record);
}