package com.seeu.task.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.seeu.task.model.TaskLocation;

public class TaskLocationSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_location
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    public String insertSelective(TaskLocation record) {
        BEGIN();
        INSERT_INTO("task_location");
        
        if (record.getTID() != null) {
            VALUES("TID", "#{TID,jdbcType=INTEGER}");
        }
        
        if (record.getPublish_location() != null) {
            VALUES("publish_location", "#{publish_location,jdbcType=VARCHAR}");
        }
        
        if (record.getPublish_province() != null) {
            VALUES("publish_province", "#{publish_province,jdbcType=VARCHAR}");
        }
        
        if (record.getPublish_city() != null) {
            VALUES("publish_city", "#{publish_city,jdbcType=VARCHAR}");
        }
        
        if (record.getTaker_province() != null) {
            VALUES("taker_province", "#{taker_province,jdbcType=VARCHAR}");
        }
        
        if (record.getTaker_city() != null) {
            VALUES("taker_city", "#{taker_city,jdbcType=VARCHAR}");
        }
        
        if (record.getTake_location() != null) {
            VALUES("take_location", "#{take_location,jdbcType=VARCHAR}");
        }
        
        if (record.getComplete_province() != null) {
            VALUES("complete_province", "#{complete_province,jdbcType=VARCHAR}");
        }
        
        if (record.getCpmplete_city() != null) {
            VALUES("cpmplete_city", "#{cpmplete_city,jdbcType=VARCHAR}");
        }
        
        if (record.getComplete_location() != null) {
            VALUES("complete_location", "#{complete_location,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_location
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    public String updateByPrimaryKeySelective(TaskLocation record) {
        BEGIN();
        UPDATE("task_location");
        
        if (record.getPublish_location() != null) {
            SET("publish_location = #{publish_location,jdbcType=VARCHAR}");
        }
        
        if (record.getPublish_province() != null) {
            SET("publish_province = #{publish_province,jdbcType=VARCHAR}");
        }
        
        if (record.getPublish_city() != null) {
            SET("publish_city = #{publish_city,jdbcType=VARCHAR}");
        }
        
        if (record.getTaker_province() != null) {
            SET("taker_province = #{taker_province,jdbcType=VARCHAR}");
        }
        
        if (record.getTaker_city() != null) {
            SET("taker_city = #{taker_city,jdbcType=VARCHAR}");
        }
        
        if (record.getTake_location() != null) {
            SET("take_location = #{take_location,jdbcType=VARCHAR}");
        }
        
        if (record.getComplete_province() != null) {
            SET("complete_province = #{complete_province,jdbcType=VARCHAR}");
        }
        
        if (record.getCpmplete_city() != null) {
            SET("cpmplete_city = #{cpmplete_city,jdbcType=VARCHAR}");
        }
        
        if (record.getComplete_location() != null) {
            SET("complete_location = #{complete_location,jdbcType=VARCHAR}");
        }
        
        WHERE("TID = #{TID,jdbcType=INTEGER}");
        
        return SQL();
    }
}