package com.seeu.task.dao;

import com.seeu.task.model.TaskLocation;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TaskLocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_location
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    @Delete({
        "delete from task_location",
        "where TID = #{TID,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer TID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_location
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    @Insert({
        "insert into task_location (TID, publish_location, ",
        "publish_province, publish_city, ",
        "taker_province, taker_city, ",
        "take_location, complete_province, ",
        "cpmplete_city, complete_location)",
        "values (#{TID,jdbcType=INTEGER}, #{publish_location,jdbcType=VARCHAR}, ",
        "#{publish_province,jdbcType=VARCHAR}, #{publish_city,jdbcType=VARCHAR}, ",
        "#{taker_province,jdbcType=VARCHAR}, #{taker_city,jdbcType=VARCHAR}, ",
        "#{take_location,jdbcType=VARCHAR}, #{complete_province,jdbcType=VARCHAR}, ",
        "#{cpmplete_city,jdbcType=VARCHAR}, #{complete_location,jdbcType=VARCHAR})"
    })
    int insert(TaskLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_location
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    @InsertProvider(type=TaskLocationSqlProvider.class, method="insertSelective")
    int insertSelective(TaskLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_location
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    @Select({
        "select",
        "TID, publish_location, publish_province, publish_city, taker_province, taker_city, ",
        "take_location, complete_province, cpmplete_city, complete_location",
        "from task_location",
        "where TID = #{TID,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="TID", property="TID", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="publish_location", property="publish_location", jdbcType=JdbcType.VARCHAR),
        @Result(column="publish_province", property="publish_province", jdbcType=JdbcType.VARCHAR),
        @Result(column="publish_city", property="publish_city", jdbcType=JdbcType.VARCHAR),
        @Result(column="taker_province", property="taker_province", jdbcType=JdbcType.VARCHAR),
        @Result(column="taker_city", property="taker_city", jdbcType=JdbcType.VARCHAR),
        @Result(column="take_location", property="take_location", jdbcType=JdbcType.VARCHAR),
        @Result(column="complete_province", property="complete_province", jdbcType=JdbcType.VARCHAR),
        @Result(column="cpmplete_city", property="cpmplete_city", jdbcType=JdbcType.VARCHAR),
        @Result(column="complete_location", property="complete_location", jdbcType=JdbcType.VARCHAR)
    })
    TaskLocation selectByPrimaryKey(Integer TID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_location
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    @UpdateProvider(type=TaskLocationSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TaskLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_location
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    @Update({
        "update task_location",
        "set publish_location = #{publish_location,jdbcType=VARCHAR},",
          "publish_province = #{publish_province,jdbcType=VARCHAR},",
          "publish_city = #{publish_city,jdbcType=VARCHAR},",
          "taker_province = #{taker_province,jdbcType=VARCHAR},",
          "taker_city = #{taker_city,jdbcType=VARCHAR},",
          "take_location = #{take_location,jdbcType=VARCHAR},",
          "complete_province = #{complete_province,jdbcType=VARCHAR},",
          "cpmplete_city = #{cpmplete_city,jdbcType=VARCHAR},",
          "complete_location = #{complete_location,jdbcType=VARCHAR}",
        "where TID = #{TID,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TaskLocation record);
}