package com.seeu.task.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.seeu.task.model.TaskBidder;

public class TaskBidderSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_bidder
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    public String insertSelective(TaskBidder record) {
        BEGIN();
        INSERT_INTO("task_bidder");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getTID() != null) {
            VALUES("TID", "#{TID,jdbcType=INTEGER}");
        }
        
        if (record.getBidderUID() != null) {
            VALUES("bidderUID", "#{bidderUID,jdbcType=INTEGER}");
        }
        
        if (record.getRole() != null) {
            VALUES("role", "#{role,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            VALUES("status", "#{status,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_bidder
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    public String updateByPrimaryKeySelective(TaskBidder record) {
        BEGIN();
        UPDATE("task_bidder");
        
        if (record.getTID() != null) {
            SET("TID = #{TID,jdbcType=INTEGER}");
        }
        
        if (record.getBidderUID() != null) {
            SET("bidderUID = #{bidderUID,jdbcType=INTEGER}");
        }
        
        if (record.getRole() != null) {
            SET("role = #{role,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            SET("status = #{status,jdbcType=INTEGER}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}