package com.seeu.task.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.seeu.task.model.TaskBasicWithBLOBs;

public class TaskBasicSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_basic
     *
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    public String insertSelective(TaskBasicWithBLOBs record) {
        BEGIN();
        INSERT_INTO("task_basic");
        
        if (record.getTID() != null) {
            VALUES("TID", "#{TID,jdbcType=INTEGER}");
        }
        
        if (record.getUID() != null) {
            VALUES("UID", "#{UID,jdbcType=INTEGER}");
        }
        
        if (record.getTitle() != null) {
            VALUES("title", "#{title,jdbcType=VARCHAR}");
        }
        
        if (record.getTime() != null) {
            VALUES("time", "#{time,jdbcType=TIMESTAMP}");
        }
        
        if (record.getTag() != null) {
            VALUES("tag", "#{tag,jdbcType=VARCHAR}");
        }
        
        if (record.getLiker_num() != null) {
            VALUES("liker_num", "#{liker_num,jdbcType=INTEGER}");
        }
        
        if (record.getRead_num() != null) {
            VALUES("read_num", "#{read_num,jdbcType=INTEGER}");
        }
        
        if (record.getComment_num() != null) {
            VALUES("comment_num", "#{comment_num,jdbcType=INTEGER}");
        }
        
        if (record.getStatus() != null) {
            VALUES("status", "#{status,jdbcType=INTEGER}");
        }
        
        if (record.getMoney() != null) {
            VALUES("money", "#{money,jdbcType=DECIMAL}");
        }
        
        if (record.getNote() != null) {
            VALUES("note", "#{note,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getPictures() != null) {
            VALUES("pictures", "#{pictures,jdbcType=LONGVARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_basic
     *
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    public String updateByPrimaryKeySelective(TaskBasicWithBLOBs record) {
        BEGIN();
        UPDATE("task_basic");
        
        if (record.getUID() != null) {
            SET("UID = #{UID,jdbcType=INTEGER}");
        }
        
        if (record.getTitle() != null) {
            SET("title = #{title,jdbcType=VARCHAR}");
        }
        
        if (record.getTime() != null) {
            SET("time = #{time,jdbcType=TIMESTAMP}");
        }
        
        if (record.getTag() != null) {
            SET("tag = #{tag,jdbcType=VARCHAR}");
        }
        
        if (record.getLiker_num() != null) {
            SET("liker_num = #{liker_num,jdbcType=INTEGER}");
        }
        
        if (record.getRead_num() != null) {
            SET("read_num = #{read_num,jdbcType=INTEGER}");
        }
        
        if (record.getComment_num() != null) {
            SET("comment_num = #{comment_num,jdbcType=INTEGER}");
        }
        
        if (record.getStatus() != null) {
            SET("status = #{status,jdbcType=INTEGER}");
        }
        
        if (record.getMoney() != null) {
            SET("money = #{money,jdbcType=DECIMAL}");
        }
        
        if (record.getNote() != null) {
            SET("note = #{note,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getPictures() != null) {
            SET("pictures = #{pictures,jdbcType=LONGVARCHAR}");
        }
        
        WHERE("TID = #{TID,jdbcType=INTEGER}");
        
        return SQL();
    }
}