package com.seeu.task.dao;

import com.seeu.task.model.TaskBidder;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface TaskBidderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_bidder
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    @Delete({
            "delete from task_bidder",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    @Delete({
            "delete from task_bidder",
            "where TID = #{TID,jdbcType=INTEGER}",
            "and bidderUID = #{UID,jdbcType=INTEGER}"
    })
    int deleteByBidderUIDandTID(Integer TID, Integer UID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_bidder
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    @Insert({
            "insert into task_bidder (id, TID, ",
            "bidderUID, role, ",
            "status)",
            "values (#{id,jdbcType=INTEGER}, #{TID,jdbcType=INTEGER}, ",
            "#{bidderUID,jdbcType=INTEGER}, #{role,jdbcType=VARCHAR}, ",
            "#{status,jdbcType=INTEGER})"
    })
    int insert(TaskBidder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_bidder
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    @InsertProvider(type = TaskBidderSqlProvider.class, method = "insertSelective")
    int insertSelective(TaskBidder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_bidder
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    @Select({
            "select",
            "id, TID, bidderUID, role, status",
            "from task_bidder",
            "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "TID", property = "TID", jdbcType = JdbcType.INTEGER),
            @Result(column = "bidderUID", property = "bidderUID", jdbcType = JdbcType.INTEGER),
            @Result(column = "role", property = "role", jdbcType = JdbcType.VARCHAR),
            @Result(column = "status", property = "status", jdbcType = JdbcType.INTEGER)
    })
    TaskBidder selectByPrimaryKey(Integer id);

    @Select({
            "select",
            "id, TID, bidderUID, role, status",
            "from task_bidder",
            "where TID = #{TID,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "TID", property = "TID", jdbcType = JdbcType.INTEGER),
            @Result(column = "bidderUID", property = "bidderUID", jdbcType = JdbcType.INTEGER),
            @Result(column = "role", property = "role", jdbcType = JdbcType.VARCHAR),
            @Result(column = "status", property = "status", jdbcType = JdbcType.INTEGER)
    })
    List<TaskBidder> selectByTID(Integer TID);

    @Select({
            "select",
            "id, TID, bidderUID, role, status",
            "from task_bidder",
            "where bidderUID = #{bidderUID,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "TID", property = "TID", jdbcType = JdbcType.INTEGER),
            @Result(column = "bidderUID", property = "bidderUID", jdbcType = JdbcType.INTEGER),
            @Result(column = "role", property = "role", jdbcType = JdbcType.VARCHAR),
            @Result(column = "status", property = "status", jdbcType = JdbcType.INTEGER)
    })
    List<TaskBidder> selectByBidderUID(Integer bidderUID);

    @Select({
            "select",
            "id, TID, bidderUID, role, status",
            "from task_bidder",
            "where TID = #{TID,jdbcType=INTEGER}",
            "and bidderUID = #{bidderUID,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "TID", property = "TID", jdbcType = JdbcType.INTEGER),
            @Result(column = "bidderUID", property = "bidderUID", jdbcType = JdbcType.INTEGER),
            @Result(column = "role", property = "role", jdbcType = JdbcType.VARCHAR),
            @Result(column = "status", property = "status", jdbcType = JdbcType.INTEGER)
    })
    TaskBidder selectByTIDandBidderUID(Integer TID, Integer bidderUID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_bidder
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    @UpdateProvider(type = TaskBidderSqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TaskBidder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_bidder
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    @Update({
            "update task_bidder",
            "set TID = #{TID,jdbcType=INTEGER},",
            "bidderUID = #{bidderUID,jdbcType=INTEGER},",
            "role = #{role,jdbcType=VARCHAR},",
            "status = #{status,jdbcType=INTEGER}",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TaskBidder record);
}