package com.seeu.task.dao;

import com.seeu.task.model.TaskTime;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TaskTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_time
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    @Delete({
        "delete from task_time",
        "where TID = #{TID,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer TID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_time
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    @Insert({
        "insert into task_time (TID, start, ",
        "end)",
        "values (#{TID,jdbcType=INTEGER}, #{start,jdbcType=TIMESTAMP}, ",
        "#{end,jdbcType=TIMESTAMP})"
    })
    int insert(TaskTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_time
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    @InsertProvider(type=TaskTimeSqlProvider.class, method="insertSelective")
    int insertSelective(TaskTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_time
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    @Select({
        "select",
        "TID, start, end",
        "from task_time",
        "where TID = #{TID,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="TID", property="TID", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="start", property="start", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="end", property="end", jdbcType=JdbcType.TIMESTAMP)
    })
    TaskTime selectByPrimaryKey(Integer TID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_time
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    @UpdateProvider(type=TaskTimeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TaskTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_time
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    @Update({
        "update task_time",
        "set start = #{start,jdbcType=TIMESTAMP},",
          "end = #{end,jdbcType=TIMESTAMP}",
        "where TID = #{TID,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TaskTime record);
}