package com.seeu.task.dao;

import com.seeu.task.model.TaskTaker;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

public interface TaskTakerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_taker
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    @Delete({
            "delete from task_taker",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_taker
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    @Insert({
            "insert into task_taker (id, TID, ",
            "takerUID, role)",
            "values (#{id,jdbcType=INTEGER}, #{TID,jdbcType=INTEGER}, ",
            "#{takerUID,jdbcType=INTEGER}, #{role,jdbcType=VARCHAR})"
    })
    int insert(TaskTaker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_taker
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    @InsertProvider(type = TaskTakerSqlProvider.class, method = "insertSelective")
    @Options(useGeneratedKeys = true, keyProperty = "id", keyColumn = "id")
    int insertSelective(TaskTaker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_taker
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    @Select({
            "select",
            "id, TID, takerUID, role",
            "from task_taker",
            "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "TID", property = "TID", jdbcType = JdbcType.INTEGER),
            @Result(column = "takerUID", property = "takerUID", jdbcType = JdbcType.INTEGER),
            @Result(column = "role", property = "role", jdbcType = JdbcType.VARCHAR)
    })
    TaskTaker selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_taker
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    @UpdateProvider(type = TaskTakerSqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TaskTaker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_taker
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    @Update({
            "update task_taker",
            "set TID = #{TID,jdbcType=INTEGER},",
            "takerUID = #{takerUID,jdbcType=INTEGER},",
            "role = #{role,jdbcType=VARCHAR}",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TaskTaker record);
}