package com.seeu.task.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.seeu.task.model.TaskTime;

public class TaskTimeSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_time
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    public String insertSelective(TaskTime record) {
        BEGIN();
        INSERT_INTO("task_time");
        
        if (record.getTID() != null) {
            VALUES("TID", "#{TID,jdbcType=INTEGER}");
        }
        
        if (record.getStart() != null) {
            VALUES("start", "#{start,jdbcType=TIMESTAMP}");
        }
        
        if (record.getEnd() != null) {
            VALUES("end", "#{end,jdbcType=TIMESTAMP}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_time
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    public String updateByPrimaryKeySelective(TaskTime record) {
        BEGIN();
        UPDATE("task_time");
        
        if (record.getStart() != null) {
            SET("start = #{start,jdbcType=TIMESTAMP}");
        }
        
        if (record.getEnd() != null) {
            SET("end = #{end,jdbcType=TIMESTAMP}");
        }
        
        WHERE("TID = #{TID,jdbcType=INTEGER}");
        
        return SQL();
    }
}