package com.seeu.task.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.seeu.task.model.TaskComment;

public class TaskCommentSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_comment
     *
     * @mbggenerated Thu Jan 19 04:28:43 CST 2017
     */
    public String insertSelective(TaskComment record) {
        BEGIN();
        INSERT_INTO("task_comment");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getTID() != null) {
            VALUES("TID", "#{TID,jdbcType=INTEGER}");
        }
        
        if (record.getCommentUID() != null) {
            VALUES("commentUID", "#{commentUID,jdbcType=INTEGER}");
        }
        
        if (record.getLiker_num() != null) {
            VALUES("liker_num", "#{liker_num,jdbcType=INTEGER}");
        }
        
        if (record.getTime() != null) {
            VALUES("time", "#{time,jdbcType=TIMESTAMP}");
        }
        
        if (record.getComment() != null) {
            VALUES("comment", "#{comment,jdbcType=LONGVARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_comment
     *
     * @mbggenerated Thu Jan 19 04:28:43 CST 2017
     */
    public String updateByPrimaryKeySelective(TaskComment record) {
        BEGIN();
        UPDATE("task_comment");
        
        if (record.getTID() != null) {
            SET("TID = #{TID,jdbcType=INTEGER}");
        }
        
        if (record.getCommentUID() != null) {
            SET("commentUID = #{commentUID,jdbcType=INTEGER}");
        }
        
        if (record.getLiker_num() != null) {
            SET("liker_num = #{liker_num,jdbcType=INTEGER}");
        }
        
        if (record.getTime() != null) {
            SET("time = #{time,jdbcType=TIMESTAMP}");
        }
        
        if (record.getComment() != null) {
            SET("comment = #{comment,jdbcType=LONGVARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}