package com.seeu.userOAuth.db.model;

public class LoginUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.UID
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    private Integer UID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.account
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.password
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.UID
     *
     * @return the value of login_user.UID
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    public Integer getUID() {
        return UID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.UID
     *
     * @param UID the value for login_user.UID
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    public void setUID(Integer UID) {
        this.UID = UID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.account
     *
     * @return the value of login_user.account
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.account
     *
     * @param account the value for login_user.account
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.password
     *
     * @return the value of login_user.password
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.password
     *
     * @param password the value for login_user.password
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }
}