package com.seeu.userOAuth.db.model;

import java.util.Date;

public class LoginLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.id
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.UID
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    private Integer UID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.ip
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.logindate
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    private Date logindate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.id
     *
     * @return the value of login_log.id
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.id
     *
     * @param id the value for login_log.id
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.UID
     *
     * @return the value of login_log.UID
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    public Integer getUID() {
        return UID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.UID
     *
     * @param UID the value for login_log.UID
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    public void setUID(Integer UID) {
        this.UID = UID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.ip
     *
     * @return the value of login_log.ip
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.ip
     *
     * @param ip the value for login_log.ip
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.logindate
     *
     * @return the value of login_log.logindate
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    public Date getLogindate() {
        return logindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.logindate
     *
     * @param logindate the value for login_log.logindate
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    public void setLogindate(Date logindate) {
        this.logindate = logindate;
    }
}