package com.seeu.user.dao;

import com.seeu.user.model.UserProject;
import com.seeu.user.model.UserProjectWithBLOBs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface UserProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_proj
     *
     * @mbggenerated Wed Jan 18 15:23:24 CST 2017
     */
    @Delete({
        "delete from user_proj",
        "where recordID = #{recordID,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer recordID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_proj
     *
     * @mbggenerated Wed Jan 18 15:23:24 CST 2017
     */
    @Insert({
        "insert into user_proj (recordID, UID, ",
        "type, title, url, ",
        "role, time_start, ",
        "time_end, note, ",
        "pictures, performance)",
        "values (#{recordID,jdbcType=INTEGER}, #{UID,jdbcType=INTEGER}, ",
        "#{type,jdbcType=VARCHAR}, #{title,jdbcType=VARCHAR}, #{url,jdbcType=VARCHAR}, ",
        "#{role,jdbcType=VARCHAR}, #{time_start,jdbcType=VARCHAR}, ",
        "#{time_end,jdbcType=VARCHAR}, #{note,jdbcType=LONGVARCHAR}, ",
        "#{pictures,jdbcType=LONGVARCHAR}, #{performance,jdbcType=LONGVARCHAR})"
    })
    int insert(UserProjectWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_proj
     *
     * @mbggenerated Wed Jan 18 15:23:24 CST 2017
     */
    @InsertProvider(type=UserProjectSqlProvider.class, method="insertSelective")
    int insertSelective(UserProjectWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_proj
     *
     * @mbggenerated Wed Jan 18 15:23:24 CST 2017
     */
    @Select({
        "select",
        "recordID, UID, type, title, url, role, time_start, time_end, note, pictures, ",
        "performance",
        "from user_proj",
        "where recordID = #{recordID,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="recordID", property="recordID", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="UID", property="UID", jdbcType=JdbcType.INTEGER),
        @Result(column="type", property="type", jdbcType=JdbcType.VARCHAR),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="role", property="role", jdbcType=JdbcType.VARCHAR),
        @Result(column="time_start", property="time_start", jdbcType=JdbcType.VARCHAR),
        @Result(column="time_end", property="time_end", jdbcType=JdbcType.VARCHAR),
        @Result(column="note", property="note", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="pictures", property="pictures", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="performance", property="performance", jdbcType=JdbcType.LONGVARCHAR)
    })
    UserProjectWithBLOBs selectByPrimaryKey(Integer recordID);

    @Select({
            "select",
//            "recordID, UID, type, title, url, role, time_start, time_end, pictures, describe, ",
            "* ",
            "from user_proj",
            "where UID = #{UID,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column="recordID", property="recordID", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="UID", property="UID", jdbcType=JdbcType.INTEGER),
            @Result(column="type", property="type", jdbcType=JdbcType.VARCHAR),
            @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
            @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR),
            @Result(column="role", property="role", jdbcType=JdbcType.VARCHAR),
            @Result(column="time_start", property="time_start", jdbcType=JdbcType.VARCHAR),
            @Result(column="time_end", property="time_end", jdbcType=JdbcType.VARCHAR),
            @Result(column="note", property="note", jdbcType=JdbcType.LONGVARCHAR),
            @Result(column="pictures", property="pictures", jdbcType=JdbcType.LONGVARCHAR),
            @Result(column="performance", property="performance", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<UserProjectWithBLOBs> selectByUID(Integer UID);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_proj
     *
     * @mbggenerated Wed Jan 18 15:23:24 CST 2017
     */
    @UpdateProvider(type=UserProjectSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(UserProjectWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_proj
     *
     * @mbggenerated Wed Jan 18 15:23:24 CST 2017
     */
    @Update({
        "update user_proj",
        "set UID = #{UID,jdbcType=INTEGER},",
          "type = #{type,jdbcType=VARCHAR},",
          "title = #{title,jdbcType=VARCHAR},",
          "url = #{url,jdbcType=VARCHAR},",
          "role = #{role,jdbcType=VARCHAR},",
          "time_start = #{time_start,jdbcType=VARCHAR},",
          "time_end = #{time_end,jdbcType=VARCHAR},",
          "note = #{note,jdbcType=LONGVARCHAR},",
          "pictures = #{pictures,jdbcType=LONGVARCHAR},",
          "performance = #{performance,jdbcType=LONGVARCHAR}",
        "where recordID = #{recordID,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(UserProjectWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_proj
     *
     * @mbggenerated Wed Jan 18 15:23:24 CST 2017
     */
    @Update({
        "update user_proj",
        "set UID = #{UID,jdbcType=INTEGER},",
          "type = #{type,jdbcType=VARCHAR},",
          "title = #{title,jdbcType=VARCHAR},",
          "url = #{url,jdbcType=VARCHAR},",
          "role = #{role,jdbcType=VARCHAR},",
          "time_start = #{time_start,jdbcType=VARCHAR},",
          "time_end = #{time_end,jdbcType=VARCHAR}",
        "where recordID = #{recordID,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserProject record);
}