package com.seeu.user.dao;

import com.seeu.user.model.UserRealProfile;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface UserRealProfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_realprofile
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    @Delete({
        "delete from user_realprofile",
        "where UID = #{UID,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer UID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_realprofile
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    @Insert({
        "insert into user_realprofile (UID, name, ",
        "idcard, gender)",
        "values (#{UID,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{idcard,jdbcType=VARCHAR}, #{gender,jdbcType=INTEGER})"
    })
    int insert(UserRealProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_realprofile
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    @InsertProvider(type=UserRealProfileSqlProvider.class, method="insertSelective")
    int insertSelective(UserRealProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_realprofile
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    @Select({
        "select",
        "UID, name, idcard, gender",
        "from user_realprofile",
        "where UID = #{UID,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="UID", property="UID", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="idcard", property="idcard", jdbcType=JdbcType.VARCHAR),
        @Result(column="gender", property="gender", jdbcType=JdbcType.INTEGER)
    })
    UserRealProfile selectByPrimaryKey(Integer UID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_realprofile
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    @UpdateProvider(type=UserRealProfileSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(UserRealProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_realprofile
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    @Update({
        "update user_realprofile",
        "set name = #{name,jdbcType=VARCHAR},",
          "idcard = #{idcard,jdbcType=VARCHAR},",
          "gender = #{gender,jdbcType=INTEGER}",
        "where UID = #{UID,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserRealProfile record);
}