package com.seeu.user.dao;

import com.seeu.user.model.UserSocialNet;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface UserSocialNetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_socialnet
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    @Delete({
        "delete from user_socialnet",
        "where UID = #{UID,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer UID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_socialnet
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    @Insert({
        "insert into user_socialnet (UID, qq, ",
        "weixin, blog, email, ",
        "phone_prefix, phone)",
        "values (#{UID,jdbcType=INTEGER}, #{qq,jdbcType=VARCHAR}, ",
        "#{weixin,jdbcType=VARCHAR}, #{blog,jdbcType=VARCHAR}, #{email,jdbcType=VARCHAR}, ",
        "#{phone_prefix,jdbcType=VARCHAR}, #{phone,jdbcType=VARCHAR})"
    })
    int insert(UserSocialNet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_socialnet
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    @InsertProvider(type=UserSocialNetSqlProvider.class, method="insertSelective")
    int insertSelective(UserSocialNet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_socialnet
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    @Select({
        "select",
        "UID, qq, weixin, blog, email, phone_prefix, phone",
        "from user_socialnet",
        "where UID = #{UID,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="UID", property="UID", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="qq", property="qq", jdbcType=JdbcType.VARCHAR),
        @Result(column="weixin", property="weixin", jdbcType=JdbcType.VARCHAR),
        @Result(column="blog", property="blog", jdbcType=JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="phone_prefix", property="phone_prefix", jdbcType=JdbcType.VARCHAR),
        @Result(column="phone", property="phone", jdbcType=JdbcType.VARCHAR)
    })
    UserSocialNet selectByPrimaryKey(Integer UID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_socialnet
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    @UpdateProvider(type=UserSocialNetSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(UserSocialNet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_socialnet
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    @Update({
        "update user_socialnet",
        "set qq = #{qq,jdbcType=VARCHAR},",
          "weixin = #{weixin,jdbcType=VARCHAR},",
          "blog = #{blog,jdbcType=VARCHAR},",
          "email = #{email,jdbcType=VARCHAR},",
          "phone_prefix = #{phone_prefix,jdbcType=VARCHAR},",
          "phone = #{phone,jdbcType=VARCHAR}",
        "where UID = #{UID,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserSocialNet record);
}