package com.seeu.user.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.seeu.user.model.UserBusiness;

public class UserBusinessSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_business
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public String insertSelective(UserBusiness record) {
        BEGIN();
        INSERT_INTO("user_business");
        
        if (record.getRecordID() != null) {
            VALUES("recordID", "#{recordID,jdbcType=INTEGER}");
        }
        
        if (record.getUID() != null) {
            VALUES("UID", "#{UID,jdbcType=INTEGER}");
        }
        
        if (record.getTime_start() != null) {
            VALUES("time_start", "#{time_start,jdbcType=VARCHAR}");
        }
        
        if (record.getTime_end() != null) {
            VALUES("time_end", "#{time_end,jdbcType=VARCHAR}");
        }
        
        if (record.getCompany() != null) {
            VALUES("company", "#{company,jdbcType=VARCHAR}");
        }
        
        if (record.getCompany_province() != null) {
            VALUES("company_province", "#{company_province,jdbcType=VARCHAR}");
        }
        
        if (record.getCompany_city() != null) {
            VALUES("company_city", "#{company_city,jdbcType=VARCHAR}");
        }
        
        if (record.getComment() != null) {
            VALUES("comment", "#{comment,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_business
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public String updateByPrimaryKeySelective(UserBusiness record) {
        BEGIN();
        UPDATE("user_business");
        
        if (record.getUID() != null) {
            SET("UID = #{UID,jdbcType=INTEGER}");
        }
        
        if (record.getTime_start() != null) {
            SET("time_start = #{time_start,jdbcType=VARCHAR}");
        }
        
        if (record.getTime_end() != null) {
            SET("time_end = #{time_end,jdbcType=VARCHAR}");
        }
        
        if (record.getCompany() != null) {
            SET("company = #{company,jdbcType=VARCHAR}");
        }
        
        if (record.getCompany_province() != null) {
            SET("company_province = #{company_province,jdbcType=VARCHAR}");
        }
        
        if (record.getCompany_city() != null) {
            SET("company_city = #{company_city,jdbcType=VARCHAR}");
        }
        
        if (record.getComment() != null) {
            SET("comment = #{comment,jdbcType=VARCHAR}");
        }
        
        WHERE("recordID = #{recordID,jdbcType=INTEGER}");
        
        return SQL();
    }
}