package com.seeu.user.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.seeu.user.model.UserEducation;

public class UserEducationSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_education
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public String insertSelective(UserEducation record) {
        BEGIN();
        INSERT_INTO("user_education");
        
        if (record.getRecordID() != null) {
            VALUES("recordID", "#{recordID,jdbcType=INTEGER}");
        }
        
        if (record.getUID() != null) {
            VALUES("UID", "#{UID,jdbcType=INTEGER}");
        }
        
        if (record.getPeriod() != null) {
            VALUES("period", "#{period,jdbcType=INTEGER}");
        }
        
        if (record.getTime_start() != null) {
            VALUES("time_start", "#{time_start,jdbcType=VARCHAR}");
        }
        
        if (record.getTime_end() != null) {
            VALUES("time_end", "#{time_end,jdbcType=VARCHAR}");
        }
        
        if (record.getSchool() != null) {
            VALUES("school", "#{school,jdbcType=VARCHAR}");
        }
        
        if (record.getSchool_province() != null) {
            VALUES("school_province", "#{school_province,jdbcType=VARCHAR}");
        }
        
        if (record.getSchool_city() != null) {
            VALUES("school_city", "#{school_city,jdbcType=VARCHAR}");
        }
        
        if (record.getComment() != null) {
            VALUES("comment", "#{comment,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_education
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    public String updateByPrimaryKeySelective(UserEducation record) {
        BEGIN();
        UPDATE("user_education");
        
        if (record.getUID() != null) {
            SET("UID = #{UID,jdbcType=INTEGER}");
        }
        
        if (record.getPeriod() != null) {
            SET("period = #{period,jdbcType=INTEGER}");
        }
        
        if (record.getTime_start() != null) {
            SET("time_start = #{time_start,jdbcType=VARCHAR}");
        }
        
        if (record.getTime_end() != null) {
            SET("time_end = #{time_end,jdbcType=VARCHAR}");
        }
        
        if (record.getSchool() != null) {
            SET("school = #{school,jdbcType=VARCHAR}");
        }
        
        if (record.getSchool_province() != null) {
            SET("school_province = #{school_province,jdbcType=VARCHAR}");
        }
        
        if (record.getSchool_city() != null) {
            SET("school_city = #{school_city,jdbcType=VARCHAR}");
        }
        
        if (record.getComment() != null) {
            SET("comment = #{comment,jdbcType=VARCHAR}");
        }
        
        WHERE("recordID = #{recordID,jdbcType=INTEGER}");
        
        return SQL();
    }
}