package com.seeu.user.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.seeu.user.model.UserBasic;

public class UserBasicSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_basic
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public String insertSelective(UserBasic record) {
        BEGIN();
        INSERT_INTO("user_basic");
        
        if (record.getUID() != null) {
            VALUES("UID", "#{UID,jdbcType=INTEGER}");
        }
        
        if (record.getIcon() != null) {
            VALUES("icon", "#{icon,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        if (record.getGender() != null) {
            VALUES("gender", "#{gender,jdbcType=TINYINT}");
        }
        
        if (record.getBirthday() != null) {
            VALUES("birthday", "#{birthday,jdbcType=VARCHAR}");
        }
        
        if (record.getSign() != null) {
            VALUES("sign", "#{sign,jdbcType=VARCHAR}");
        }
        
        if (record.getLocation_province() != null) {
            VALUES("location_province", "#{location_province,jdbcType=VARCHAR}");
        }
        
        if (record.getLocation_city() != null) {
            VALUES("location_city", "#{location_city,jdbcType=VARCHAR}");
        }
        
        if (record.getHome_province() != null) {
            VALUES("home_province", "#{home_province,jdbcType=VARCHAR}");
        }
        
        if (record.getHome_city() != null) {
            VALUES("home_city", "#{home_city,jdbcType=VARCHAR}");
        }
        
        if (record.getRegister_time() != null) {
            VALUES("register_time", "#{register_time,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_basic
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public String updateByPrimaryKeySelective(UserBasic record) {
        BEGIN();
        UPDATE("user_basic");
        
        if (record.getIcon() != null) {
            SET("icon = #{icon,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        if (record.getGender() != null) {
            SET("gender = #{gender,jdbcType=TINYINT}");
        }
        
        if (record.getBirthday() != null) {
            SET("birthday = #{birthday,jdbcType=VARCHAR}");
        }
        
        if (record.getSign() != null) {
            SET("sign = #{sign,jdbcType=VARCHAR}");
        }
        
        if (record.getLocation_province() != null) {
            SET("location_province = #{location_province,jdbcType=VARCHAR}");
        }
        
        if (record.getLocation_city() != null) {
            SET("location_city = #{location_city,jdbcType=VARCHAR}");
        }
        
        if (record.getHome_province() != null) {
            SET("home_province = #{home_province,jdbcType=VARCHAR}");
        }
        
        if (record.getHome_city() != null) {
            SET("home_city = #{home_city,jdbcType=VARCHAR}");
        }
        
        if (record.getRegister_time() != null) {
            SET("register_time = #{register_time,jdbcType=VARCHAR}");
        }
        
        WHERE("UID = #{UID,jdbcType=INTEGER}");
        
        return SQL();
    }
}