package com.seeu.user.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.seeu.user.model.UserSocialNet;

public class UserSocialNetSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_socialnet
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public String insertSelective(UserSocialNet record) {
        BEGIN();
        INSERT_INTO("user_socialnet");
        
        if (record.getUID() != null) {
            VALUES("UID", "#{UID,jdbcType=INTEGER}");
        }
        
        if (record.getQq() != null) {
            VALUES("qq", "#{qq,jdbcType=VARCHAR}");
        }
        
        if (record.getWeixin() != null) {
            VALUES("weixin", "#{weixin,jdbcType=VARCHAR}");
        }
        
        if (record.getBlog() != null) {
            VALUES("blog", "#{blog,jdbcType=VARCHAR}");
        }
        
        if (record.getEmail() != null) {
            VALUES("email", "#{email,jdbcType=VARCHAR}");
        }
        
        if (record.getPhone_prefix() != null) {
            VALUES("phone_prefix", "#{phone_prefix,jdbcType=VARCHAR}");
        }
        
        if (record.getPhone() != null) {
            VALUES("phone", "#{phone,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_socialnet
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public String updateByPrimaryKeySelective(UserSocialNet record) {
        BEGIN();
        UPDATE("user_socialnet");
        
        if (record.getQq() != null) {
            SET("qq = #{qq,jdbcType=VARCHAR}");
        }
        
        if (record.getWeixin() != null) {
            SET("weixin = #{weixin,jdbcType=VARCHAR}");
        }
        
        if (record.getBlog() != null) {
            SET("blog = #{blog,jdbcType=VARCHAR}");
        }
        
        if (record.getEmail() != null) {
            SET("email = #{email,jdbcType=VARCHAR}");
        }
        
        if (record.getPhone_prefix() != null) {
            SET("phone_prefix = #{phone_prefix,jdbcType=VARCHAR}");
        }
        
        if (record.getPhone() != null) {
            SET("phone = #{phone,jdbcType=VARCHAR}");
        }
        
        WHERE("UID = #{UID,jdbcType=INTEGER}");
        
        return SQL();
    }
}