package com.seeu.user.dao;

import com.seeu.user.model.UserBusiness;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface UserBusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_business
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    @Delete({
            "delete from user_business",
            "where recordID = #{recordID,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer recordID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_business
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    @Insert({
            "insert into user_business (recordID, UID, ",
            "time_start, time_end, ",
            "company, company_province, ",
            "company_city, comment)",
            "values (#{recordID,jdbcType=INTEGER}, #{UID,jdbcType=INTEGER}, ",
            "#{time_start,jdbcType=VARCHAR}, #{time_end,jdbcType=VARCHAR}, ",
            "#{company,jdbcType=VARCHAR}, #{company_province,jdbcType=VARCHAR}, ",
            "#{company_city,jdbcType=VARCHAR}, #{comment,jdbcType=VARCHAR})"
    })
    int insert(UserBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_business
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    @InsertProvider(type = UserBusinessSqlProvider.class, method = "insertSelective")
    int insertSelective(UserBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_business
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    @Select({
            "select",
            "recordID, UID, time_start, time_end, company, company_province, company_city, ",
            "comment",
            "from user_business",
            "where recordID = #{recordID,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column = "recordID", property = "recordID", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "UID", property = "UID", jdbcType = JdbcType.INTEGER),
            @Result(column = "time_start", property = "time_start", jdbcType = JdbcType.VARCHAR),
            @Result(column = "time_end", property = "time_end", jdbcType = JdbcType.VARCHAR),
            @Result(column = "company", property = "company", jdbcType = JdbcType.VARCHAR),
            @Result(column = "company_province", property = "company_province", jdbcType = JdbcType.VARCHAR),
            @Result(column = "company_city", property = "company_city", jdbcType = JdbcType.VARCHAR),
            @Result(column = "comment", property = "comment", jdbcType = JdbcType.VARCHAR)
    })
    UserBusiness selectByPrimaryKey(Integer recordID);


    @Select({
            "select",
            "recordID, UID, time_start, time_end, company, company_province, company_city, ",
            "comment",
            "from user_business",
            "where UID = #{UID,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column = "recordID", property = "recordID", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "UID", property = "UID", jdbcType = JdbcType.INTEGER),
            @Result(column = "time_start", property = "time_start", jdbcType = JdbcType.VARCHAR),
            @Result(column = "time_end", property = "time_end", jdbcType = JdbcType.VARCHAR),
            @Result(column = "company", property = "company", jdbcType = JdbcType.VARCHAR),
            @Result(column = "company_province", property = "company_province", jdbcType = JdbcType.VARCHAR),
            @Result(column = "company_city", property = "company_city", jdbcType = JdbcType.VARCHAR),
            @Result(column = "comment", property = "comment", jdbcType = JdbcType.VARCHAR)
    })
    List<UserBusiness> selectByUID(Integer recordID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_business
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    @UpdateProvider(type = UserBusinessSqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(UserBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_business
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    @Update({
            "update user_business",
            "set UID = #{UID,jdbcType=INTEGER},",
            "time_start = #{time_start,jdbcType=VARCHAR},",
            "time_end = #{time_end,jdbcType=VARCHAR},",
            "company = #{company,jdbcType=VARCHAR},",
            "company_province = #{company_province,jdbcType=VARCHAR},",
            "company_city = #{company_city,jdbcType=VARCHAR},",
            "comment = #{comment,jdbcType=VARCHAR}",
            "where recordID = #{recordID,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserBusiness record);
}