package com.seeu.user.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.seeu.user.model.UserRealProfile;

public class UserRealProfileSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_realprofile
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public String insertSelective(UserRealProfile record) {
        BEGIN();
        INSERT_INTO("user_realprofile");
        
        if (record.getUID() != null) {
            VALUES("UID", "#{UID,jdbcType=INTEGER}");
        }
        
        if (record.getName() != null) {
            VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        if (record.getIdcard() != null) {
            VALUES("idcard", "#{idcard,jdbcType=VARCHAR}");
        }
        
        if (record.getGender() != null) {
            VALUES("gender", "#{gender,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_realprofile
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public String updateByPrimaryKeySelective(UserRealProfile record) {
        BEGIN();
        UPDATE("user_realprofile");
        
        if (record.getName() != null) {
            SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        if (record.getIdcard() != null) {
            SET("idcard = #{idcard,jdbcType=VARCHAR}");
        }
        
        if (record.getGender() != null) {
            SET("gender = #{gender,jdbcType=INTEGER}");
        }
        
        WHERE("UID = #{UID,jdbcType=INTEGER}");
        
        return SQL();
    }
}