package com.seeu.user.dao;

import com.seeu.user.model.UserEducation;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface UserEducationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_education
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    @Delete({
            "delete from user_education",
            "where recordID = #{recordID,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer recordID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_education
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    @Insert({
            "insert into user_education (recordID, UID, ",
            "period, time_start, ",
            "time_end, school, ",
            "school_province, school_city, ",
            "comment)",
            "values (#{recordID,jdbcType=INTEGER}, #{UID,jdbcType=INTEGER}, ",
            "#{period,jdbcType=INTEGER}, #{time_start,jdbcType=VARCHAR}, ",
            "#{time_end,jdbcType=VARCHAR}, #{school,jdbcType=VARCHAR}, ",
            "#{school_province,jdbcType=VARCHAR}, #{school_city,jdbcType=VARCHAR}, ",
            "#{comment,jdbcType=VARCHAR})"
    })
    int insert(UserEducation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_education
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    @InsertProvider(type = UserEducationSqlProvider.class, method = "insertSelective")
    int insertSelective(UserEducation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_education
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    @Select({
            "select",
            "recordID, UID, period, time_start, time_end, school, school_province, school_city, ",
            "comment",
            "from user_education",
            "where recordID = #{recordID,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column = "recordID", property = "recordID", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "UID", property = "UID", jdbcType = JdbcType.INTEGER),
            @Result(column = "period", property = "period", jdbcType = JdbcType.INTEGER),
            @Result(column = "time_start", property = "time_start", jdbcType = JdbcType.VARCHAR),
            @Result(column = "time_end", property = "time_end", jdbcType = JdbcType.VARCHAR),
            @Result(column = "school", property = "school", jdbcType = JdbcType.VARCHAR),
            @Result(column = "school_province", property = "school_province", jdbcType = JdbcType.VARCHAR),
            @Result(column = "school_city", property = "school_city", jdbcType = JdbcType.VARCHAR),
            @Result(column = "comment", property = "comment", jdbcType = JdbcType.VARCHAR)
    })
    UserEducation selectByPrimaryKey(Integer recordID);

    @Select({
            "select",
            "recordID, UID, period, time_start, time_end, school, school_province, school_city, ",
            "comment",
            "from user_education",
            "where UID = #{UID,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column = "recordID", property = "recordID", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "UID", property = "UID", jdbcType = JdbcType.INTEGER),
            @Result(column = "period", property = "period", jdbcType = JdbcType.INTEGER),
            @Result(column = "time_start", property = "time_start", jdbcType = JdbcType.VARCHAR),
            @Result(column = "time_end", property = "time_end", jdbcType = JdbcType.VARCHAR),
            @Result(column = "school", property = "school", jdbcType = JdbcType.VARCHAR),
            @Result(column = "school_province", property = "school_province", jdbcType = JdbcType.VARCHAR),
            @Result(column = "school_city", property = "school_city", jdbcType = JdbcType.VARCHAR),
            @Result(column = "comment", property = "comment", jdbcType = JdbcType.VARCHAR)
    })
    List<UserEducation> selectByUID(Integer UID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_education
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    @UpdateProvider(type = UserEducationSqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(UserEducation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_education
     *
     * @mbggenerated Tue Jan 17 17:29:58 CST 2017
     */
    @Update({
            "update user_education",
            "set UID = #{UID,jdbcType=INTEGER},",
            "period = #{period,jdbcType=INTEGER},",
            "time_start = #{time_start,jdbcType=VARCHAR},",
            "time_end = #{time_end,jdbcType=VARCHAR},",
            "school = #{school,jdbcType=VARCHAR},",
            "school_province = #{school_province,jdbcType=VARCHAR},",
            "school_city = #{school_city,jdbcType=VARCHAR},",
            "comment = #{comment,jdbcType=VARCHAR}",
            "where recordID = #{recordID,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserEducation record);
}