package com.seeu.user.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.seeu.user.model.UserInterest;

public class UserInterestSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_interest
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public String insertSelective(UserInterest record) {
        BEGIN();
        INSERT_INTO("user_interest");
        
        if (record.getUID() != null) {
            VALUES("UID", "#{UID,jdbcType=INTEGER}");
        }
        
        if (record.getLabel() != null) {
            VALUES("label", "#{label,jdbcType=LONGVARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_interest
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    public String updateByPrimaryKeySelective(UserInterest record) {
        BEGIN();
        UPDATE("user_interest");
        
        if (record.getLabel() != null) {
            SET("label = #{label,jdbcType=LONGVARCHAR}");
        }
        
        WHERE("UID = #{UID,jdbcType=INTEGER}");
        
        return SQL();
    }
}