package com.seeu.user.dao;

import com.seeu.user.model.UserBasic;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface UserBasicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_basic
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    @Delete({
            "delete from user_basic",
            "where UID = #{UID,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer UID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_basic
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    @Insert({
            "insert into user_basic (UID, icon, ",
            "name, gender, birthday, ",
            "sign, location_province, ",
            "location_city, home_province, ",
            "home_city, register_time)",
            "values (#{UID,jdbcType=INTEGER}, #{icon,jdbcType=VARCHAR}, ",
            "#{name,jdbcType=VARCHAR}, #{gender,jdbcType=TINYINT}, #{birthday,jdbcType=VARCHAR}, ",
            "#{sign,jdbcType=VARCHAR}, #{location_province,jdbcType=VARCHAR}, ",
            "#{location_city,jdbcType=VARCHAR}, #{home_province,jdbcType=VARCHAR}, ",
            "#{home_city,jdbcType=VARCHAR}, #{register_time,jdbcType=VARCHAR})"
    })
    int insert(UserBasic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_basic
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    @InsertProvider(type = UserBasicSqlProvider.class, method = "insertSelective")
    int insertSelective(UserBasic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_basic
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    @Select({
            "select",
            "UID, icon, name, gender, birthday, sign, location_province, location_city, home_province, ",
            "home_city, register_time",
            "from user_basic",
            "where UID = #{UID,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column = "UID", property = "UID", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "icon", property = "icon", jdbcType = JdbcType.VARCHAR),
            @Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR),
            @Result(column = "gender", property = "gender", jdbcType = JdbcType.TINYINT),
            @Result(column = "birthday", property = "birthday", jdbcType = JdbcType.VARCHAR),
            @Result(column = "sign", property = "sign", jdbcType = JdbcType.VARCHAR),
            @Result(column = "location_province", property = "location_province", jdbcType = JdbcType.VARCHAR),
            @Result(column = "location_city", property = "location_city", jdbcType = JdbcType.VARCHAR),
            @Result(column = "home_province", property = "home_province", jdbcType = JdbcType.VARCHAR),
            @Result(column = "home_city", property = "home_city", jdbcType = JdbcType.VARCHAR),
            @Result(column = "register_time", property = "register_time", jdbcType = JdbcType.VARCHAR)
    })
    UserBasic selectByPrimaryKey(Integer UID);

    @Select({
            "select",
            "UID, icon, name, gender, sign ",
            "from user_basic",
            "where UID = #{UID,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column = "UID", property = "UID", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "icon", property = "icon", jdbcType = JdbcType.VARCHAR),
            @Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR),
            @Result(column = "gender", property = "gender", jdbcType = JdbcType.TINYINT),
            @Result(column = "sign", property = "sign", jdbcType = JdbcType.VARCHAR)
    })
    UserBasic selectPureByPrimaryKey(Integer UID);

    @Select({
            "select",
            "UID, name",
            "from user_basic",
            "where name = #{name,jdbcType=VARCHAR}"
    })
    @Results({
            @Result(column = "UID", property = "UID", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR)
    })
    UserBasic selectByName(String name);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_basic
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    @UpdateProvider(type = UserBasicSqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(UserBasic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_basic
     *
     * @mbggenerated Sat Jan 14 14:13:51 CST 2017
     */
    @Update({
            "update user_basic",
            "set icon = #{icon,jdbcType=VARCHAR},",
            "name = #{name,jdbcType=VARCHAR},",
            "gender = #{gender,jdbcType=TINYINT},",
            "birthday = #{birthday,jdbcType=VARCHAR},",
            "sign = #{sign,jdbcType=VARCHAR},",
            "location_province = #{location_province,jdbcType=VARCHAR},",
            "location_city = #{location_city,jdbcType=VARCHAR},",
            "home_province = #{home_province,jdbcType=VARCHAR},",
            "home_city = #{home_city,jdbcType=VARCHAR},",
            "register_time = #{register_time,jdbcType=VARCHAR}",
            "where UID = #{UID,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserBasic record);
}