package com.seeu.task.model;

import java.math.BigDecimal;
import java.util.Date;

public class TaskBasic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_basic.TID
     *
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    private Integer TID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_basic.UID
     *
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    private Integer UID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_basic.title
     *
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_basic.time
     *
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    private Date time;

    /**
     * tag 是任务标签、类型
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_basic.liker_num
     *
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    private Integer liker_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_basic.read_num
     *
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    private Integer read_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_basic.comment_num
     *
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    private Integer comment_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_basic.status
     *
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_basic.money
     *
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    private BigDecimal money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_basic.TID
     *
     * @return the value of task_basic.TID
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    public Integer getTID() {
        return TID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_basic.TID
     *
     * @param TID the value for task_basic.TID
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    public void setTID(Integer TID) {
        this.TID = TID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_basic.UID
     *
     * @return the value of task_basic.UID
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    public Integer getUID() {
        return UID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_basic.UID
     *
     * @param UID the value for task_basic.UID
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    public void setUID(Integer UID) {
        this.UID = UID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_basic.title
     *
     * @return the value of task_basic.title
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_basic.title
     *
     * @param title the value for task_basic.title
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_basic.time
     *
     * @return the value of task_basic.time
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_basic.time
     *
     * @param time the value for task_basic.time
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_basic.tag
     *
     * @return the value of task_basic.tag
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_basic.tag
     *
     * @param tag the value for task_basic.tag
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_basic.liker_num
     *
     * @return the value of task_basic.liker_num
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    public Integer getLiker_num() {
        return liker_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_basic.liker_num
     *
     * @param liker_num the value for task_basic.liker_num
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    public void setLiker_num(Integer liker_num) {
        this.liker_num = liker_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_basic.read_num
     *
     * @return the value of task_basic.read_num
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    public Integer getRead_num() {
        return read_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_basic.read_num
     *
     * @param read_num the value for task_basic.read_num
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    public void setRead_num(Integer read_num) {
        this.read_num = read_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_basic.comment_num
     *
     * @return the value of task_basic.comment_num
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    public Integer getComment_num() {
        return comment_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_basic.comment_num
     *
     * @param comment_num the value for task_basic.comment_num
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    public void setComment_num(Integer comment_num) {
        this.comment_num = comment_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_basic.status
     *
     * @return the value of task_basic.status
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_basic.status
     *
     * @param status the value for task_basic.status
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_basic.money
     *
     * @return the value of task_basic.money
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_basic.money
     *
     * @param money the value for task_basic.money
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }
}