package com.seeu.task.model;

import java.util.Date;

public class TaskComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_comment.id
     *
     * @mbggenerated Thu Jan 19 04:28:43 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_comment.TID
     *
     * @mbggenerated Thu Jan 19 04:28:43 CST 2017
     */
    private Integer TID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_comment.commentUID
     *
     * @mbggenerated Thu Jan 19 04:28:43 CST 2017
     */
    private Integer commentUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_comment.liker_num
     *
     * @mbggenerated Thu Jan 19 04:28:43 CST 2017
     */
    private Integer liker_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_comment.time
     *
     * @mbggenerated Thu Jan 19 04:28:43 CST 2017
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_comment.comment
     *
     * @mbggenerated Thu Jan 19 04:28:43 CST 2017
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_comment.id
     *
     * @return the value of task_comment.id
     *
     * @mbggenerated Thu Jan 19 04:28:43 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_comment.id
     *
     * @param id the value for task_comment.id
     *
     * @mbggenerated Thu Jan 19 04:28:43 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_comment.TID
     *
     * @return the value of task_comment.TID
     *
     * @mbggenerated Thu Jan 19 04:28:43 CST 2017
     */
    public Integer getTID() {
        return TID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_comment.TID
     *
     * @param TID the value for task_comment.TID
     *
     * @mbggenerated Thu Jan 19 04:28:43 CST 2017
     */
    public void setTID(Integer TID) {
        this.TID = TID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_comment.commentUID
     *
     * @return the value of task_comment.commentUID
     *
     * @mbggenerated Thu Jan 19 04:28:43 CST 2017
     */
    public Integer getCommentUID() {
        return commentUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_comment.commentUID
     *
     * @param commentUID the value for task_comment.commentUID
     *
     * @mbggenerated Thu Jan 19 04:28:43 CST 2017
     */
    public void setCommentUID(Integer commentUID) {
        this.commentUID = commentUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_comment.liker_num
     *
     * @return the value of task_comment.liker_num
     *
     * @mbggenerated Thu Jan 19 04:28:43 CST 2017
     */
    public Integer getLiker_num() {
        return liker_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_comment.liker_num
     *
     * @param liker_num the value for task_comment.liker_num
     *
     * @mbggenerated Thu Jan 19 04:28:43 CST 2017
     */
    public void setLiker_num(Integer liker_num) {
        this.liker_num = liker_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_comment.time
     *
     * @return the value of task_comment.time
     *
     * @mbggenerated Thu Jan 19 04:28:43 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_comment.time
     *
     * @param time the value for task_comment.time
     *
     * @mbggenerated Thu Jan 19 04:28:43 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_comment.comment
     *
     * @return the value of task_comment.comment
     *
     * @mbggenerated Thu Jan 19 04:28:43 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_comment.comment
     *
     * @param comment the value for task_comment.comment
     *
     * @mbggenerated Thu Jan 19 04:28:43 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment;
    }
}