package com.seeu.task.model;

public class TaskBidder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_bidder.id
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_bidder.TID
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    private Integer TID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_bidder.bidderUID
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    private Integer bidderUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_bidder.role
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_bidder.status
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_bidder.id
     *
     * @return the value of task_bidder.id
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_bidder.id
     *
     * @param id the value for task_bidder.id
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_bidder.TID
     *
     * @return the value of task_bidder.TID
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    public Integer getTID() {
        return TID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_bidder.TID
     *
     * @param TID the value for task_bidder.TID
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    public void setTID(Integer TID) {
        this.TID = TID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_bidder.bidderUID
     *
     * @return the value of task_bidder.bidderUID
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    public Integer getBidderUID() {
        return bidderUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_bidder.bidderUID
     *
     * @param bidderUID the value for task_bidder.bidderUID
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    public void setBidderUID(Integer bidderUID) {
        this.bidderUID = bidderUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_bidder.role
     *
     * @return the value of task_bidder.role
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_bidder.role
     *
     * @param role the value for task_bidder.role
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_bidder.status
     *
     * @return the value of task_bidder.status
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_bidder.status
     *
     * @param status the value for task_bidder.status
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}