package com.seeu.task.model;

public class TaskTaker {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_taker.id
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_taker.TID
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    private Integer TID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_taker.takerUID
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    private Integer takerUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_taker.role
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    private String role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_taker.id
     *
     * @return the value of task_taker.id
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_taker.id
     *
     * @param id the value for task_taker.id
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_taker.TID
     *
     * @return the value of task_taker.TID
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    public Integer getTID() {
        return TID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_taker.TID
     *
     * @param TID the value for task_taker.TID
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    public void setTID(Integer TID) {
        this.TID = TID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_taker.takerUID
     *
     * @return the value of task_taker.takerUID
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    public Integer getTakerUID() {
        return takerUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_taker.takerUID
     *
     * @param takerUID the value for task_taker.takerUID
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    public void setTakerUID(Integer takerUID) {
        this.takerUID = takerUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_taker.role
     *
     * @return the value of task_taker.role
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_taker.role
     *
     * @param role the value for task_taker.role
     *
     * @mbggenerated Thu Jan 19 15:05:24 CST 2017
     */
    public void setRole(String role) {
        this.role = role;
    }
}