package com.seeu.task.model;

public class TaskLocation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_location.TID
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    private Integer TID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_location.publish_location
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    private String publish_location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_location.publish_province
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    private String publish_province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_location.publish_city
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    private String publish_city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_location.taker_province
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    private String taker_province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_location.taker_city
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    private String taker_city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_location.take_location
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    private String take_location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_location.complete_province
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    private String complete_province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_location.cpmplete_city
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    private String cpmplete_city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_location.complete_location
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    private String complete_location;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_location.TID
     *
     * @return the value of task_location.TID
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    public Integer getTID() {
        return TID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_location.TID
     *
     * @param TID the value for task_location.TID
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    public void setTID(Integer TID) {
        this.TID = TID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_location.publish_location
     *
     * @return the value of task_location.publish_location
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    public String getPublish_location() {
        return publish_location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_location.publish_location
     *
     * @param publish_location the value for task_location.publish_location
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    public void setPublish_location(String publish_location) {
        this.publish_location = publish_location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_location.publish_province
     *
     * @return the value of task_location.publish_province
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    public String getPublish_province() {
        return publish_province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_location.publish_province
     *
     * @param publish_province the value for task_location.publish_province
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    public void setPublish_province(String publish_province) {
        this.publish_province = publish_province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_location.publish_city
     *
     * @return the value of task_location.publish_city
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    public String getPublish_city() {
        return publish_city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_location.publish_city
     *
     * @param publish_city the value for task_location.publish_city
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    public void setPublish_city(String publish_city) {
        this.publish_city = publish_city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_location.taker_province
     *
     * @return the value of task_location.taker_province
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    public String getTaker_province() {
        return taker_province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_location.taker_province
     *
     * @param taker_province the value for task_location.taker_province
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    public void setTaker_province(String taker_province) {
        this.taker_province = taker_province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_location.taker_city
     *
     * @return the value of task_location.taker_city
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    public String getTaker_city() {
        return taker_city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_location.taker_city
     *
     * @param taker_city the value for task_location.taker_city
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    public void setTaker_city(String taker_city) {
        this.taker_city = taker_city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_location.take_location
     *
     * @return the value of task_location.take_location
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    public String getTake_location() {
        return take_location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_location.take_location
     *
     * @param take_location the value for task_location.take_location
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    public void setTake_location(String take_location) {
        this.take_location = take_location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_location.complete_province
     *
     * @return the value of task_location.complete_province
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    public String getComplete_province() {
        return complete_province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_location.complete_province
     *
     * @param complete_province the value for task_location.complete_province
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    public void setComplete_province(String complete_province) {
        this.complete_province = complete_province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_location.cpmplete_city
     *
     * @return the value of task_location.cpmplete_city
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    public String getCpmplete_city() {
        return cpmplete_city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_location.cpmplete_city
     *
     * @param cpmplete_city the value for task_location.cpmplete_city
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    public void setCpmplete_city(String cpmplete_city) {
        this.cpmplete_city = cpmplete_city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_location.complete_location
     *
     * @return the value of task_location.complete_location
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    public String getComplete_location() {
        return complete_location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_location.complete_location
     *
     * @param complete_location the value for task_location.complete_location
     *
     * @mbggenerated Wed Jan 18 05:06:10 CST 2017
     */
    public void setComplete_location(String complete_location) {
        this.complete_location = complete_location;
    }
}