package com.seeu.task.model;

public class TaskBasicWithBLOBs extends TaskBasic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_basic.note
     *
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_basic.pictures
     *
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    private String pictures;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_basic.note
     *
     * @return the value of task_basic.note
     *
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_basic.note
     *
     * @param note the value for task_basic.note
     *
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_basic.pictures
     *
     * @return the value of task_basic.pictures
     *
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    public String getPictures() {
        return pictures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_basic.pictures
     *
     * @param pictures the value for task_basic.pictures
     *
     * @mbggenerated Thu Jan 19 18:24:25 CST 2017
     */
    public void setPictures(String pictures) {
        this.pictures = pictures;
    }
}