package com.seeu.userOAuth.db.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.seeu.userOAuth.db.model.LoginLog;

public class LoginLogSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_log
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    public String insertSelective(LoginLog record) {
        BEGIN();
        INSERT_INTO("login_log");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getUID() != null) {
            VALUES("UID", "#{UID,jdbcType=INTEGER}");
        }
        
        if (record.getIp() != null) {
            VALUES("ip", "#{ip,jdbcType=VARCHAR}");
        }
        
        if (record.getLogindate() != null) {
            VALUES("logindate", "#{logindate,jdbcType=TIMESTAMP}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_log
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    public String updateByPrimaryKeySelective(LoginLog record) {
        BEGIN();
        UPDATE("login_log");
        
        if (record.getUID() != null) {
            SET("UID = #{UID,jdbcType=INTEGER}");
        }
        
        if (record.getIp() != null) {
            SET("ip = #{ip,jdbcType=VARCHAR}");
        }
        
        if (record.getLogindate() != null) {
            SET("logindate = #{logindate,jdbcType=TIMESTAMP}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}