package com.seeu.userOAuth.db.dao;

import com.seeu.userOAuth.db.model.LoginUser;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface LoginUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    @Delete({
            "delete from login_user",
            "where UID = #{UID,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer UID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    @Insert({
            "insert into login_user (UID, account, ",
            "password)",
            "values (#{UID,jdbcType=INTEGER}, #{account,jdbcType=VARCHAR}, ",
            "#{password,jdbcType=VARCHAR})"
    })
    int insert(LoginUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    @InsertProvider(type = LoginUserSqlProvider.class, method = "insertSelective")
    int insertSelective(LoginUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    @Select({
            "select",
            "UID, account, password",
            "from login_user",
            "where UID = #{UID,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column = "UID", property = "UID", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "account", property = "account", jdbcType = JdbcType.VARCHAR),
            @Result(column = "password", property = "password", jdbcType = JdbcType.VARCHAR)
    })
    LoginUser selectByPrimaryKey(Integer UID);


    @Select({
            "select",
            "UID, account, password",
            "from login_user",
            "where account = #{account,jdbcType=VARCHAR}"
    })
    @Results({
            @Result(column = "UID", property = "UID", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "account", property = "account", jdbcType = JdbcType.VARCHAR),
            @Result(column = "password", property = "password", jdbcType = JdbcType.VARCHAR)
    })
    LoginUser selectByAccount(String account);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    @UpdateProvider(type = LoginUserSqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(LoginUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    @Update({
            "update login_user",
            "set account = #{account,jdbcType=VARCHAR},",
            "password = #{password,jdbcType=VARCHAR}",
            "where UID = #{UID,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(LoginUser record);
}