package com.seeu.userOAuth.db.dao;

import com.seeu.userOAuth.db.model.LoginLog;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface LoginLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_log
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    @Delete({
        "delete from login_log",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_log
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    @Insert({
        "insert into login_log (id, UID, ",
        "ip, logindate)",
        "values (#{id,jdbcType=INTEGER}, #{UID,jdbcType=INTEGER}, ",
        "#{ip,jdbcType=VARCHAR}, #{logindate,jdbcType=TIMESTAMP})"
    })
    int insert(LoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_log
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    @InsertProvider(type=LoginLogSqlProvider.class, method="insertSelective")
    int insertSelective(LoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_log
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    @Select({
        "select",
        "id, UID, ip, logindate",
        "from login_log",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="UID", property="UID", jdbcType=JdbcType.INTEGER),
        @Result(column="ip", property="ip", jdbcType=JdbcType.VARCHAR),
        @Result(column="logindate", property="logindate", jdbcType=JdbcType.TIMESTAMP)
    })
    LoginLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_log
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    @UpdateProvider(type=LoginLogSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(LoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_log
     *
     * @mbggenerated Sat Jan 14 14:16:27 CST 2017
     */
    @Update({
        "update login_log",
        "set UID = #{UID,jdbcType=INTEGER},",
          "ip = #{ip,jdbcType=VARCHAR},",
          "logindate = #{logindate,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(LoginLog record);
}